[package]
name = "minihactool"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]

[dependencies]
byteorder = "1.2.1"
bit_field = "0.9.0"
itertools = "0.7.8"
serde_json = "1.0.13"
serde_derive = "1.0.35"
serde = "1.0.35"
walkdir = "2.1.4"
